### ISSUE TITLE
Module import issue 

### ISSUE THREAD

**Issue by alpeshster** [jconsoli/brocade-rest-api-examples#1]
I tried to copy the packages from   brcddb and  brcdapi   but when tried to run a sample script it gives me beow error 

(tutorial-env) sbeadmin@pdk-mg-sanas-01 $ python capture.py –ip 10.5.104.71 –id admin –pw d@ng3rZ –s self –f chassis_data.json
Traceback (most recent call last):
  File "capture.py", line 60, in <module>
    import brcddb.brcddb_project as brcddb_project
  File "/home/sbeadmin/tutorial-env/lib64/python3.6/site-packages/brcddb/brcddb_project.py", line 52, in <module>
    import brcddb.brcddb_fabric as brcddb_fabric
  File "/home/sbeadmin/tutorial-env/lib64/python3.6/site-packages/brcddb/brcddb_fabric.py", line 42, in <module>
    import brcddb.util.util as brcddb_util
  File "/home/sbeadmin/tutorial-env/lib64/python3.6/site-packages/brcddb/util/util.py", line 40, in <module>
    import brcddb.util.search as brcddb_search
  File "/home/sbeadmin/tutorial-env/lib64/python3.6/site-packages/brcddb/util/search.py", line 53, in <module>
    import brcddb.util.util as brcddb_util
AttributeError: module 'brcddb.util' has no attribute 'util'

**Comment by jconsoli** [comment]
This should be fixed now.

**Comment by ALutz273** [comment]
Same error

python3 api_get_examples.py -ip  xx.x.x.x  -id powervc -pw 'xxxxxx' –s self –fid 128 -d
Traceback (most recent call last):
  File "api_get_examples.py", line 66, in <module>
    import brcdapi.brcdapi_rest as brcdapi_rest
  File "/root/test/brocade-rest-api-examples-main/brcdapi/brcdapi_rest.py", line 92, in <module>
    import brcdapi.fos_auth as fos_auth
  File "/root/test/brocade-rest-api-examples-main/brcdapi/fos_auth.py", line 130, in <module>
    import brcdapi.util as brcdapi_util
  File "/root/test/brocade-rest-api-examples-main/brcdapi/util.py", line 100, in <module>
    import brcdapi.gen_util as gen_util
  File "/root/test/brocade-rest-api-examples-main/brcdapi/gen_util.py", line 118, in <module>
    import brcddb.classes.util as brcddb_class_util
  File "/root/test/brocade-rest-api-examples-main/brcddb/classes/util.py", line 55, in <module>
    import brcdapi.gen_util as gen_util
AttributeError: module 'brcdapi' has no attribute 'gen_util'

**Comment by jconsoli** [comment]
My apologies. I uploaded a stale file. To fix this, take the latest version of brcdapi/gen_util.py. I also updated lib_check.py

**Comment by ALutz273** [comment]
With this version it worked without problems. Thanks for the update.
